export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpg",
    username: "Kandyboo",
  },
  {
    id:2,
    profilePicture: "assets/person/2.jpeg",
    username: "Bubuu",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpeg",
    username: "Anh Bay Cho",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpeg",
    username: "Solitude",
  },
];

export const Posts = [
  {
    id: 1,
    desc: " Police Dogs Reverent Plea: A Touching Gesture of Prayers for Owner s Safety Leaves Many in Awe ",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: " Heartwarming Story: Meet the Market Dogs Who Sell Veggies to Support Their Owner  ",
    photo: "assets/post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Wallace: The Corgi with a Heart-Shaped Nose Who Spreads Love, One Hug at a Time ",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    desc: "Rescuing a Neglected Pooch from an Abandoned Barn: His Trembles Left the Rescue Team Heartbroken.",
    photo: "assets/post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    desc: "The Brave Puppy’s Pitiful Cry: A Tale of Courage, Motherhood, and an Unexpected Savior",
    photo: "assets/post/5.jpeg", 
    date: "5 hours ago",
    userId: 2,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: 2,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Paws of Hope: The Incredible Bond Between a Loyal Dog and a Brave Hospital-Bound Child",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 2,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    userId: 3,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Apologies, Mom, I forgot my key. 🙄",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: 4,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    desc: "Unbelievable Wonder: A Mother Dog's Miracle - 18 Chubby Puppies!",
    photo: "assets/post/10.jpeg",
    date: "1 week ago",
    userId: 2,
    like: 104,
    comment: 12,
  },
];
